### ISSUE TITLE
Crashes with any action

### ISSUE THREAD

**Issue by NokTham** [WaxMoon/MultiApp#10]
V1.0.3
Android 10
Custom ROM: ResurrectionRemix

`time: 1670756061987
msg: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
stacktrace: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
	at com.hack.opensdk.HackApi.installPackageFromHost(HackApi.java:44)
	at org.waxmoon.AppListActivityKt$install$1.invoke(AppListActivity.kt:254)
	at org.waxmoon.AppListActivityKt$install$1.invoke(AppListActivity.kt:253)
	at org.waxmoon.AppListActivityKt$ApkItem$1$2$2$1.invoke(AppListActivity.kt:216)
	at org.waxmoon.AppListActivityKt$ApkItem$1$2$2$1.invoke(AppListActivity.kt:216)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke-k-4lQ0M(Clickable.kt:137)
	at androidx.compose.foundation.ClickableKt$clickable$4$gesture$1$2.invoke(Clickable.kt:137)
	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1$1.invokeSuspend(TapGestureDetector.kt:378)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:178)
	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:166)
	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:397)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:431)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:420)
	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:328)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:432)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.dispatchPointerEvent(SuspendingPointerInputFilter.kt:330)
	at androidx.compose.ui.input.pointer.SuspendingPointerInputFilter.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:343)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:287)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:275)
	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:151)
	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:90)
	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-gBdvCQM(PointerInputEventProcessor.kt:77)
	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:860)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3060)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2755)
	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:465)
	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1850)
	at android.app.Activity.dispatchTouchEvent(Activity.java:4011)
	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:423)
	at android.view.View.dispatchPointerEvent(View.java:14213)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5654)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:5452)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:5114)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:5171)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:5008)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4974)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4982)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4955)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:7685)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:7654)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:7615)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7810)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:189)
	at android.os.MessageQueue.nativePollOnce(Native Method)
	at android.os.MessageQueue.next(MessageQueue.java:336)
	at android.os.Looper.loop(Looper.java:174)
	at android.app.ActivityThread.main(ActivityThread.java:7398)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:940)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [androidx.compose.runtime.BroadcastFrameClock@42b4ed, StandaloneCoroutine{Cancelling}@bd56f22, AndroidUiDispatcher@808ddb3`

**Comment by Luciogi** [comment]
use 64bit apk https://github.com/WaxMoon/MultiApp/releases

**Comment by NokTham** [comment]
*facepalm*
Thank you xD

I had it installed through Neo Store (f-droid similar) which seems to be using IzzyOnDroid F-Droid Repo, which only has the 32bit version.
