### ISSUE TITLE
无法登录 使用google账号的应用

### ISSUE THREAD

**Issue by hhhaiai** [WaxMoon/MultiApp#3]
## 设备
* vivo iQOO Neo
* android 10

## 操作步骤
1. Enable Google Play, 测试"Open Google play"成功
2. install app， toast : success
3. start app, 广告，长时间等待，然后弹出错误（12501）

## 错误12501
![Screenshot_20221128_110408](https://user-images.githubusercontent.com/5738285/204182687-e98e0577-6bc6-4ffb-90e9-9623718ec3b5.png)

* 日志
[error-log.txt](https://github.com/WaxMoon/MultiApp/files/10100117/error-log.txt)

**Comment by hhhaiai** [comment]
明显报错
<img width="756" alt="image" src="https://user-images.githubusercontent.com/5738285/204183451-ed137605-420f-4408-86b4-55300ab1d1b4.png">
<img width="1054" alt="image" src="https://user-images.githubusercontent.com/5738285/204183490-1e971c53-a578-4e5c-9d85-a56731c5937a.png">
<img width="683" alt="image" src="https://user-images.githubusercontent.com/5738285/204183656-840514ab-0f0d-48e6-b07d-870c378da2a2.png">

**Comment by WaxMoon** [comment]
> ## 设备
> * vivo iQOO Neo
> * android 10
> 
> ## 操作步骤
> 1. Enable Google Play, 测试"Open Google play"成功
> 2. install app， toast : success
> 3. start app, 广告，长时间等待，然后弹出错误（12501）
> 
> ## 错误12501
> ![Screenshot_20221128_110408](https://user-images.githubusercontent.com/5738285/204182687-e98e0577-6bc6-4ffb-90e9-9623718ec3b5.png)
> 
> * 日志
>   [error-log.txt](https://github.com/WaxMoon/MultiApp/files/10100117/error-log.txt)

Thanks a lot! We're looking for a solution to fix this problem!

**Comment by hhhaiai** [comment]
thx

**Comment by WaxMoon** [comment]
> 

You can try v1.0.2 to verify this issue! I hope you can feed back the result to me! Tks!

**Comment by hhhaiai** [comment]
还是不行呀

```
2022-12-07 16:36:42.753 10190-10190/? W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@ff57d99
    
    --------- beginning of system
2022-12-07 16:36:42.785 10190-10190/? I/PhoneWindow: initSystemUIColor
2022-12-07 16:36:42.816 10190-10190/? W/System.err: com.google.android.gms.common.api.ApiException: 12500: 
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(Unknown Source:14)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source:30)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at com.bo.hooked.account.login.b.a(Unknown Source:4)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at com.bo.hooked.account.login.d.a(Unknown Source:7)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at com.bo.hooked.account.ui.activity.login.LoginActivity.onActivityResult(Unknown Source:5)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at android.app.Activity.dispatchActivityResult(Activity.java:8215)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at android.app.ActivityThread.deliverResults(ActivityThread.java:5312)
2022-12-07 16:36:42.816 10190-10190/? W/System.err:     at android.app.ActivityThread.handleSendResult(ActivityThread.java:5360)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:107)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.os.Looper.loop(Looper.java:230)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:7997)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
2022-12-07 16:36:42.817 10190-10190/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

```

**Comment by hhhaiai** [comment]
功能特别稳定，赞
